import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import Head from "next/head";
import "./globals.css";
import Navbar from "@/components/Navbar";

// import fontGilroyBold from "@/assets/fonts/title.woff2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MarsWTF",
  description: "Generated by create next app",
};

const style = `
  <style>
    @font-face {
      font-family: "text";
      font-style: normal;
      font-weight: 100 900;
      font-display: optional;
      src: url('../public/fonts/text.woff2') format("woff2");
    }
    @font-face {
      font-family: "title";
      font-style: normal;
      font-weight: 100 900;
      font-display: optional;
      src: url('../public/fonts/title.woff2') format("woff2");
    }
    @font-face {
      font-family: "ugly";
      font-style: normal;
      font-weight: 100 900;
      font-display: optional;
      src: url('../public/fonts/ugly.woff2') format("woff2");
    }
    .title{
      font-family: title;
    }
    .text{
      font-family: text;
    }
    .ugly{
      font-family: ugly;
    }
  </style>
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <html lang="en" className={inter.className} suppressHydrationWarning={true}>
      <Head>
        <link
          rel="preload"
          href="/fonts/text.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/title.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/ugly.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Head>
      <body lang="en" suppressHydrationWarning={true}>
        <main className="bg-white">
          {children}
        </main>
        <footer className="py-3 mt-24 text-center text-slate-500 text-2xl font-[title]">Copyright 2024</footer>
      </body>
    </html>
  );
}
